// Generated by scripts/api_contract.py. Do not edit by hand.

export interface AgentModelDeployment {
  api_base?: string | null;
  deployment_id: string;
  deployment_name?: string | null;
  is_fallback?: boolean;
  is_primary?: boolean;
  model: string;
  provider: string;
  source: string;
}

export interface AgentModelsResponse {
  models: Array<AgentModelDeployment>;
}

export interface AnalysisReport {
  details?: ReportDetails | null;
  meta: ReportMeta;
  strategy?: ReportStrategy | null;
  summary: ReportSummary;
}

export interface AnalysisResultResponse {
  created_at: string;
  query_id: string;
  report?: unknown | null;
  stock_code: string;
  stock_name?: string | null;
}

export interface AnalyzeRequest {
  async_mode?: boolean;
  force_refresh?: boolean;
  notify?: boolean;
  original_query?: string | null;
  report_type?: string;
  selection_source?: string | null;
  stock_code?: string | null;
  stock_codes?: Array<string> | null;
  stock_name?: string | null;
}

export interface AuthSettingsRequest {
  authEnabled: boolean;
  currentPassword?: string;
  password?: string;
  passwordConfirm?: string | null;
}

export interface BacktestResultItem {
  actual_movement?: string | null;
  actual_return_pct?: number | null;
  analysis_date?: string | null;
  analysis_history_id: number;
  code: string;
  direction_correct?: boolean | null;
  direction_expected?: string | null;
  end_close?: number | null;
  engine_version: string;
  eval_status: string;
  eval_window_days: number;
  evaluated_at?: string | null;
  first_hit?: string | null;
  first_hit_date?: string | null;
  first_hit_trading_days?: number | null;
  hit_stop_loss?: boolean | null;
  hit_take_profit?: boolean | null;
  max_high?: number | null;
  min_low?: number | null;
  operation_advice?: string | null;
  outcome?: string | null;
  position_recommendation?: string | null;
  simulated_entry_price?: number | null;
  simulated_exit_price?: number | null;
  simulated_exit_reason?: string | null;
  simulated_return_pct?: number | null;
  start_price?: number | null;
  stock_name?: string | null;
  stock_return_pct?: number | null;
  stop_loss?: number | null;
  take_profit?: number | null;
  trend_prediction?: string | null;
}

export interface BacktestResultsResponse {
  items?: Array<BacktestResultItem>;
  limit: number;
  page: number;
  total: number;
}

export interface BacktestRunRequest {
  code?: string | null;
  eval_window_days?: number | null;
  force?: boolean;
  limit?: number;
  min_age_days?: number | null;
}

export interface BacktestRunResponse {
  completed: number;
  errors: number;
  insufficient: number;
  processed: number;
  saved: number;
}

export interface BatchDuplicateTaskItem {
  existing_task_id: string;
  message: string;
  stock_code: string;
}

export interface BatchTaskAcceptedItem {
  message?: string | null;
  status: string;
  stock_code: string;
  task_id: string;
}

export interface BatchTaskAcceptedResponse {
  accepted?: Array<BatchTaskAcceptedItem>;
  duplicates?: Array<BatchDuplicateTaskItem>;
  message: string;
}

export interface Body_commit_csv_import_api_v1_portfolio_imports_csv_commit_post {
  account_id: number;
  broker: string;
  dry_run?: boolean;
  file: string;
}

export interface Body_extract_from_image_api_v1_stocks_extract_from_image_post {
  file?: string | null;
}

export interface Body_parse_csv_import_api_v1_portfolio_imports_csv_parse_post {
  broker: string;
  file: string;
}

export interface CallTypeBreakdown {
  call_type: string;
  calls: number;
  total_tokens: number;
}

export interface ChangePasswordRequest {
  currentPassword?: string;
  newPassword?: string;
  newPasswordConfirm?: string;
}

export interface ChatRequest {
  context?: Record<string, unknown> | null;
  message: string;
  session_id?: string | null;
  skills?: Array<string> | null;
}

export interface ChatResponse {
  content: string;
  error?: string | null;
  session_id: string;
  success: boolean;
}

export interface ConfigValidationIssue {
  actual?: string | null;
  code: string;
  expected?: string | null;
  key: string;
  message: string;
  severity: "error" | "warning";
}

export interface DeleteHistoryRequest {
  record_ids?: Array<number>;
}

export interface DeleteHistoryResponse {
  deleted: number;
}

export interface DiscoverLLMChannelModelsRequest {
  api_key?: string;
  base_url?: string;
  models?: Array<string>;
  name?: string;
  protocol?: string;
  timeout_seconds?: number;
}

export interface DiscoverLLMChannelModelsResponse {
  error?: string | null;
  latency_ms?: number | null;
  message: string;
  models?: Array<string>;
  resolved_protocol?: string | null;
  success: boolean;
}

export interface DuplicateTaskErrorResponse {
  error?: string;
  existing_task_id: string;
  message: string;
  stock_code: string;
}

export interface ErrorResponse {
  detail?: unknown | null;
  error: string;
  message: string;
}

export interface ExportSystemConfigResponse {
  config_version: string;
  content: string;
  updated_at?: string | null;
}

export interface ExtractFromImageResponse {
  codes: Array<string>;
  items?: Array<ExtractItem>;
  raw_text?: string | null;
}

export interface ExtractItem {
  code?: string | null;
  confidence?: string;
  name?: string | null;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HealthResponse {
  status: string;
  timestamp?: string | null;
}

export interface HistoryItem {
  created_at?: string | null;
  id?: number | null;
  operation_advice?: string | null;
  query_id: string;
  report_type?: string | null;
  sentiment_score?: number | null;
  stock_code: string;
  stock_name?: string | null;
}

export interface HistoryListResponse {
  items?: Array<HistoryItem>;
  limit: number;
  page: number;
  total: number;
}

export interface ImportSystemConfigRequest {
  config_version: string;
  content: string;
  reload_now?: boolean;
}

export interface KLineData {
  amount?: number | null;
  change_percent?: number | null;
  close: number;
  date: string;
  high: number;
  low: number;
  open: number;
  volume?: number | null;
}

export interface LoginRequest {
  password?: string;
  passwordConfirm?: string | null;
}

export interface MarkdownReportResponse {
  content: string;
}

export interface MarketReviewRunRequest {
  region?: "cn" | "us" | "both";
  send_notification?: boolean;
}

export interface MarketReviewRunResponse {
  notification_sent: boolean;
  region: "cn" | "us" | "both";
  report: string;
  status: "completed";
}

export interface ModelBreakdown {
  calls: number;
  model: string;
  total_tokens: number;
}

export interface NewsIntelItem {
  snippet?: string;
  title: string;
  url: string;
}

export interface NewsIntelResponse {
  items?: Array<NewsIntelItem>;
  total: number;
}

export interface PerformanceMetrics {
  advice_breakdown?: Record<string, unknown>;
  ambiguous_rate?: number | null;
  avg_days_to_first_hit?: number | null;
  avg_simulated_return_pct?: number | null;
  avg_stock_return_pct?: number | null;
  cash_count: number;
  code?: string | null;
  completed_count: number;
  computed_at?: string | null;
  diagnostics?: Record<string, unknown>;
  direction_accuracy_pct?: number | null;
  engine_version: string;
  eval_window_days: number;
  insufficient_count: number;
  long_count: number;
  loss_count: number;
  neutral_count: number;
  neutral_rate_pct?: number | null;
  scope: string;
  stop_loss_trigger_rate?: number | null;
  take_profit_trigger_rate?: number | null;
  total_evaluations: number;
  win_count: number;
  win_rate_pct?: number | null;
}

export interface PortfolioAccountCreateRequest {
  base_currency?: string;
  broker?: string | null;
  market?: "cn" | "hk" | "us";
  name: string;
  owner_id?: string | null;
}

export interface PortfolioAccountItem {
  base_currency: string;
  broker?: string | null;
  created_at?: string | null;
  id: number;
  is_active: boolean;
  market: string;
  name: string;
  owner_id?: string | null;
  updated_at?: string | null;
}

export interface PortfolioAccountListResponse {
  accounts?: Array<PortfolioAccountItem>;
}

export interface PortfolioAccountSnapshot {
  account_id: number;
  account_name: string;
  as_of: string;
  base_currency: string;
  broker?: string | null;
  cost_method: string;
  fee_total: number;
  fx_stale: boolean;
  market: string;
  owner_id?: string | null;
  positions?: Array<PortfolioPositionItem>;
  realized_pnl: number;
  tax_total: number;
  total_cash: number;
  total_equity: number;
  total_market_value: number;
  unrealized_pnl: number;
}

export interface PortfolioAccountUpdateRequest {
  base_currency?: string | null;
  broker?: string | null;
  is_active?: boolean | null;
  market?: "cn" | "hk" | "us" | null;
  name?: string | null;
  owner_id?: string | null;
}

export interface PortfolioCashLedgerCreateRequest {
  account_id: number;
  amount: number;
  currency?: string | null;
  direction: "in" | "out";
  event_date: string;
  note?: string | null;
}

export interface PortfolioCashLedgerListItem {
  account_id: number;
  amount: number;
  created_at?: string | null;
  currency: string;
  direction: string;
  event_date: string;
  id: number;
  note?: string | null;
}

export interface PortfolioCashLedgerListResponse {
  items?: Array<PortfolioCashLedgerListItem>;
  page: number;
  page_size: number;
  total: number;
}

export interface PortfolioCorporateActionCreateRequest {
  account_id: number;
  action_type: "cash_dividend" | "split_adjustment";
  cash_dividend_per_share?: number | null;
  currency?: string | null;
  effective_date: string;
  market?: "cn" | "hk" | "us" | null;
  note?: string | null;
  split_ratio?: number | null;
  symbol: string;
}

export interface PortfolioCorporateActionListItem {
  account_id: number;
  action_type: string;
  cash_dividend_per_share?: number | null;
  created_at?: string | null;
  currency: string;
  effective_date: string;
  id: number;
  market: string;
  note?: string | null;
  split_ratio?: number | null;
  symbol: string;
}

export interface PortfolioCorporateActionListResponse {
  items?: Array<PortfolioCorporateActionListItem>;
  page: number;
  page_size: number;
  total: number;
}

export interface PortfolioDeleteResponse {
  deleted: number;
}

export interface PortfolioEventCreatedResponse {
  id: number;
}

export interface PortfolioFxRefreshResponse {
  account_count: number;
  as_of: string;
  disabled_reason?: string | null;
  error_count: number;
  pair_count: number;
  refresh_enabled: boolean;
  stale_count: number;
  updated_count: number;
}

export interface PortfolioImportBrokerItem {
  aliases?: Array<string>;
  broker: string;
  display_name?: string | null;
}

export interface PortfolioImportBrokerListResponse {
  brokers?: Array<PortfolioImportBrokerItem>;
}

export interface PortfolioImportCommitResponse {
  account_id: number;
  dry_run: boolean;
  duplicate_count: number;
  errors?: Array<string>;
  failed_count: number;
  inserted_count: number;
  record_count: number;
}

export interface PortfolioImportParseResponse {
  broker: string;
  error_count: number;
  errors?: Array<string>;
  record_count: number;
  records?: Array<PortfolioImportTradeItem>;
  skipped_count: number;
}

export interface PortfolioImportTradeItem {
  currency?: string | null;
  dedup_hash: string;
  fee: number;
  price: number;
  quantity: number;
  side: "buy" | "sell";
  symbol: string;
  tax: number;
  trade_date: string;
  trade_uid?: string | null;
}

export interface PortfolioPositionItem {
  avg_cost: number;
  currency: string;
  last_price: number;
  market: string;
  market_value_base: number;
  quantity: number;
  symbol: string;
  total_cost: number;
  unrealized_pnl_base: number;
  valuation_currency: string;
}

export interface PortfolioRiskResponse {
  account_id?: number | null;
  as_of: string;
  concentration?: Record<string, unknown>;
  cost_method: string;
  currency: string;
  drawdown?: Record<string, unknown>;
  sector_concentration?: Record<string, unknown>;
  stop_loss?: Record<string, unknown>;
  thresholds?: Record<string, unknown>;
}

export interface PortfolioSnapshotResponse {
  account_count: number;
  accounts?: Array<PortfolioAccountSnapshot>;
  as_of: string;
  cost_method: string;
  currency: string;
  fee_total: number;
  fx_stale: boolean;
  realized_pnl: number;
  tax_total: number;
  total_cash: number;
  total_equity: number;
  total_market_value: number;
  unrealized_pnl: number;
}

export interface PortfolioTradeCreateRequest {
  account_id: number;
  currency?: string | null;
  fee?: number;
  market?: "cn" | "hk" | "us" | null;
  note?: string | null;
  price: number;
  quantity: number;
  side: "buy" | "sell";
  symbol: string;
  tax?: number;
  trade_date: string;
  trade_uid?: string | null;
}

export interface PortfolioTradeListItem {
  account_id: number;
  created_at?: string | null;
  currency: string;
  fee: number;
  id: number;
  market: string;
  note?: string | null;
  price: number;
  quantity: number;
  side: string;
  symbol: string;
  tax: number;
  trade_date: string;
  trade_uid?: string | null;
}

export interface PortfolioTradeListResponse {
  items?: Array<PortfolioTradeListItem>;
  page: number;
  page_size: number;
  total: number;
}

export interface QueueCapacityErrorResponse {
  current: number;
  error?: string;
  limit: number;
  message: string;
  requested: number;
}

export interface ReportDetails {
  belong_boards?: unknown | null;
  context_snapshot?: unknown | null;
  dividend_metrics?: unknown | null;
  financial_report?: unknown | null;
  news_content?: string | null;
  raw_result?: unknown | null;
  sector_rankings?: unknown | null;
}

export interface ReportMeta {
  change_pct?: number | null;
  created_at?: string | null;
  current_price?: number | null;
  id?: number | null;
  model_used?: string | null;
  query_id: string;
  report_language?: string | null;
  report_type?: string | null;
  stock_code: string;
  stock_name?: string | null;
}

export interface ReportStrategy {
  ideal_buy?: string | null;
  secondary_buy?: string | null;
  stop_loss?: string | null;
  take_profit?: string | null;
}

export interface ReportSummary {
  analysis_summary?: string | null;
  operation_advice?: string | null;
  sentiment_label?: string | null;
  sentiment_score?: number | null;
  trend_prediction?: string | null;
}

export interface ResearchRequest {
  question: string;
  stock_code?: string | null;
}

export interface ResearchResponse {
  content: string;
  error?: string | null;
  sources?: Array<string>;
  success: boolean;
  token_usage?: number;
}

export interface SendChatRequest {
  content: string;
  title?: string | null;
}

export interface SessionItem {
  created_at?: string | null;
  last_active?: string | null;
  message_count: number;
  session_id: string;
  title: string;
}

export interface SessionMessagesResponse {
  messages: Array<Record<string, unknown>>;
  session_id: string;
}

export interface SessionsResponse {
  sessions: Array<SessionItem>;
}

export interface SkillInfo {
  description: string;
  id: string;
  name: string;
}

export interface SkillsResponse {
  default_skill_id?: string;
  skills: Array<SkillInfo>;
}

export interface StockHistoryResponse {
  data?: Array<KLineData>;
  period: string;
  stock_code: string;
  stock_name?: string | null;
}

export interface StockQuote {
  amount?: number | null;
  change?: number | null;
  change_percent?: number | null;
  current_price: number;
  high?: number | null;
  low?: number | null;
  open?: number | null;
  prev_close?: number | null;
  stock_code: string;
  stock_name?: string | null;
  update_time?: string | null;
  volume?: number | null;
}

export interface SystemConfigCategorySchema {
  category: string;
  description?: string | null;
  display_order: number;
  fields: Array<SystemConfigFieldSchema>;
  title: string;
}

export interface SystemConfigConflictResponse {
  current_config_version: string;
  error: string;
  message: string;
}

export interface SystemConfigFieldSchema {
  category: "base" | "data_source" | "ai_model" | "notification" | "system" | "agent" | "backtest" | "uncategorized";
  data_type: "string" | "integer" | "number" | "boolean" | "array" | "json" | "time";
  default_value?: string | null;
  description?: string | null;
  display_order: number;
  is_editable: boolean;
  is_required: boolean;
  is_sensitive: boolean;
  key: string;
  options?: Array<string | SystemConfigOption>;
  title?: string | null;
  ui_control: "text" | "password" | "number" | "select" | "textarea" | "switch" | "time";
  validation?: Record<string, unknown>;
}

export interface SystemConfigItem {
  is_masked: boolean;
  key: string;
  raw_value_exists: boolean;
  schema?: SystemConfigFieldSchema | null;
  value: string;
}

export interface SystemConfigOption {
  label: string;
  value: string;
}

export interface SystemConfigResponse {
  config_version: string;
  items: Array<SystemConfigItem>;
  mask_token: string;
  updated_at?: string | null;
}

export interface SystemConfigSchemaResponse {
  categories: Array<SystemConfigCategorySchema>;
  schema_version: string;
}

export interface SystemConfigUpdateItem {
  key: string;
  value: string;
}

export interface SystemConfigValidationErrorResponse {
  error: string;
  issues: Array<ConfigValidationIssue>;
  message: string;
}

export interface TaskAccepted {
  message?: string | null;
  status: string;
  task_id: string;
}

export interface TaskCancelResponse {
  message: string;
  status: TaskStatusEnum;
  task_id: string;
}

export type TaskFailureTypeEnum = "validation" | "data_source" | "llm" | "notification" | "timeout" | "internal" | "cancelled";

export interface TaskInfo {
  completed_at?: string | null;
  created_at: string;
  error?: string | null;
  failure_type?: TaskFailureTypeEnum | null;
  max_retries?: number;
  message?: string | null;
  original_query?: string | null;
  progress?: number;
  report_type?: string;
  retry_count?: number;
  selection_source?: string | null;
  started_at?: string | null;
  status: TaskStatusEnum;
  stock_code: string;
  stock_name?: string | null;
  task_id: string;
}

export interface TaskListResponse {
  pending: number;
  processing: number;
  tasks: Array<TaskInfo>;
  total: number;
}

export interface TaskStatus {
  error?: string | null;
  failure_type?: TaskFailureTypeEnum | null;
  max_retries?: number;
  original_query?: string | null;
  progress?: number | null;
  result?: AnalysisResultResponse | null;
  retry_count?: number;
  selection_source?: string | null;
  status: string;
  stock_name?: string | null;
  task_id: string;
}

export type TaskStatusEnum = "pending" | "processing" | "completed" | "failed" | "cancelled" | "timeout";

export interface TestLLMChannelRequest {
  api_key?: string;
  base_url?: string;
  enabled?: boolean;
  models?: Array<string>;
  name?: string;
  protocol?: string;
  timeout_seconds?: number;
}

export interface TestLLMChannelResponse {
  error?: string | null;
  latency_ms?: number | null;
  message: string;
  resolved_model?: string | null;
  resolved_protocol?: string | null;
  success: boolean;
}

export interface UpdateSystemConfigRequest {
  config_version: string;
  items: Array<SystemConfigUpdateItem>;
  mask_token?: string;
  reload_now?: boolean;
}

export interface UpdateSystemConfigResponse {
  applied_count: number;
  config_version: string;
  reload_triggered: boolean;
  skipped_masked_count: number;
  success: boolean;
  updated_keys: Array<string>;
  warnings?: Array<string>;
}

export interface UsageSummaryResponse {
  by_call_type: Array<CallTypeBreakdown>;
  by_model: Array<ModelBreakdown>;
  from_date: string;
  period: string;
  to_date: string;
  total_calls: number;
  total_tokens: number;
}

export interface ValidateSystemConfigRequest {
  items: Array<SystemConfigUpdateItem>;
}

export interface ValidateSystemConfigResponse {
  issues: Array<ConfigValidationIssue>;
  valid: boolean;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export interface ApiOperations {
  getApiHealth: {
    method: "GET";
    path: "/api/health";
    request: never;
    response: HealthResponse;
  };
  postApiV1AgentChat: {
    method: "POST";
    path: "/api/v1/agent/chat";
    request: ChatRequest;
    response: ChatResponse | HTTPValidationError;
  };
  postApiV1AgentChatSend: {
    method: "POST";
    path: "/api/v1/agent/chat/send";
    request: SendChatRequest;
    response: HTTPValidationError;
  };
  getApiV1AgentChatSessions: {
    method: "GET";
    path: "/api/v1/agent/chat/sessions";
    request: never;
    response: SessionsResponse | HTTPValidationError;
  };
  deleteApiV1AgentChatSessionsBySessionId: {
    method: "DELETE";
    path: "/api/v1/agent/chat/sessions/{session_id}";
    request: never;
    response: HTTPValidationError;
  };
  getApiV1AgentChatSessionsBySessionId: {
    method: "GET";
    path: "/api/v1/agent/chat/sessions/{session_id}";
    request: never;
    response: SessionMessagesResponse | HTTPValidationError;
  };
  postApiV1AgentChatStream: {
    method: "POST";
    path: "/api/v1/agent/chat/stream";
    request: ChatRequest;
    response: HTTPValidationError;
  };
  getApiV1AgentModels: {
    method: "GET";
    path: "/api/v1/agent/models";
    request: never;
    response: AgentModelsResponse;
  };
  postApiV1AgentResearch: {
    method: "POST";
    path: "/api/v1/agent/research";
    request: ResearchRequest;
    response: ResearchResponse | HTTPValidationError;
  };
  getApiV1AgentSkills: {
    method: "GET";
    path: "/api/v1/agent/skills";
    request: never;
    response: SkillsResponse;
  };
  postApiV1AnalysisAnalyze: {
    method: "POST";
    path: "/api/v1/analysis/analyze";
    request: AnalyzeRequest;
    response: AnalysisResultResponse | TaskAccepted | BatchTaskAcceptedResponse | ErrorResponse | DuplicateTaskErrorResponse | HTTPValidationError | QueueCapacityErrorResponse;
  };
  getApiV1AnalysisStatusByTaskId: {
    method: "GET";
    path: "/api/v1/analysis/status/{task_id}";
    request: never;
    response: TaskStatus | ErrorResponse | HTTPValidationError;
  };
  getApiV1AnalysisTasks: {
    method: "GET";
    path: "/api/v1/analysis/tasks";
    request: never;
    response: TaskListResponse | HTTPValidationError;
  };
  getApiV1AnalysisTasksStream: {
    method: "GET";
    path: "/api/v1/analysis/tasks/stream";
    request: never;
    response: unknown;
  };
  postApiV1AnalysisTasksByTaskIdCancel: {
    method: "POST";
    path: "/api/v1/analysis/tasks/{task_id}/cancel";
    request: never;
    response: TaskCancelResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1AuthChangePassword: {
    method: "POST";
    path: "/api/v1/auth/change-password";
    request: ChangePasswordRequest;
    response: HTTPValidationError;
  };
  postApiV1AuthLogin: {
    method: "POST";
    path: "/api/v1/auth/login";
    request: LoginRequest;
    response: HTTPValidationError;
  };
  postApiV1AuthLogout: {
    method: "POST";
    path: "/api/v1/auth/logout";
    request: never;
    response: unknown;
  };
  postApiV1AuthSettings: {
    method: "POST";
    path: "/api/v1/auth/settings";
    request: AuthSettingsRequest;
    response: HTTPValidationError;
  };
  getApiV1AuthStatus: {
    method: "GET";
    path: "/api/v1/auth/status";
    request: never;
    response: unknown;
  };
  getApiV1BacktestPerformance: {
    method: "GET";
    path: "/api/v1/backtest/performance";
    request: never;
    response: PerformanceMetrics | ErrorResponse | HTTPValidationError;
  };
  getApiV1BacktestPerformanceByCode: {
    method: "GET";
    path: "/api/v1/backtest/performance/{code}";
    request: never;
    response: PerformanceMetrics | ErrorResponse | HTTPValidationError;
  };
  getApiV1BacktestResults: {
    method: "GET";
    path: "/api/v1/backtest/results";
    request: never;
    response: BacktestResultsResponse | HTTPValidationError | ErrorResponse;
  };
  postApiV1BacktestRun: {
    method: "POST";
    path: "/api/v1/backtest/run";
    request: BacktestRunRequest;
    response: BacktestRunResponse | HTTPValidationError | ErrorResponse;
  };
  deleteApiV1History: {
    method: "DELETE";
    path: "/api/v1/history";
    request: DeleteHistoryRequest;
    response: DeleteHistoryResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1History: {
    method: "GET";
    path: "/api/v1/history";
    request: never;
    response: HistoryListResponse | HTTPValidationError | ErrorResponse;
  };
  getApiV1HistoryByRecordId: {
    method: "GET";
    path: "/api/v1/history/{record_id}";
    request: never;
    response: AnalysisReport | ErrorResponse | HTTPValidationError;
  };
  getApiV1HistoryByRecordIdMarkdown: {
    method: "GET";
    path: "/api/v1/history/{record_id}/markdown";
    request: never;
    response: MarkdownReportResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1HistoryByRecordIdNews: {
    method: "GET";
    path: "/api/v1/history/{record_id}/news";
    request: never;
    response: NewsIntelResponse | HTTPValidationError | ErrorResponse;
  };
  postApiV1MarketReviewRun: {
    method: "POST";
    path: "/api/v1/market-review/run";
    request: MarketReviewRunRequest;
    response: MarketReviewRunResponse | HTTPValidationError | ErrorResponse;
  };
  getApiV1PortfolioAccounts: {
    method: "GET";
    path: "/api/v1/portfolio/accounts";
    request: never;
    response: PortfolioAccountListResponse | HTTPValidationError | ErrorResponse;
  };
  postApiV1PortfolioAccounts: {
    method: "POST";
    path: "/api/v1/portfolio/accounts";
    request: PortfolioAccountCreateRequest;
    response: PortfolioAccountItem | ErrorResponse | HTTPValidationError;
  };
  deleteApiV1PortfolioAccountsByAccountId: {
    method: "DELETE";
    path: "/api/v1/portfolio/accounts/{account_id}";
    request: never;
    response: ErrorResponse | HTTPValidationError;
  };
  putApiV1PortfolioAccountsByAccountId: {
    method: "PUT";
    path: "/api/v1/portfolio/accounts/{account_id}";
    request: PortfolioAccountUpdateRequest;
    response: PortfolioAccountItem | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioCashLedger: {
    method: "GET";
    path: "/api/v1/portfolio/cash-ledger";
    request: never;
    response: PortfolioCashLedgerListResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1PortfolioCashLedger: {
    method: "POST";
    path: "/api/v1/portfolio/cash-ledger";
    request: PortfolioCashLedgerCreateRequest;
    response: PortfolioEventCreatedResponse | ErrorResponse | HTTPValidationError;
  };
  deleteApiV1PortfolioCashLedgerByEntryId: {
    method: "DELETE";
    path: "/api/v1/portfolio/cash-ledger/{entry_id}";
    request: never;
    response: PortfolioDeleteResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioCorporateActions: {
    method: "GET";
    path: "/api/v1/portfolio/corporate-actions";
    request: never;
    response: PortfolioCorporateActionListResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1PortfolioCorporateActions: {
    method: "POST";
    path: "/api/v1/portfolio/corporate-actions";
    request: PortfolioCorporateActionCreateRequest;
    response: PortfolioEventCreatedResponse | ErrorResponse | HTTPValidationError;
  };
  deleteApiV1PortfolioCorporateActionsByActionId: {
    method: "DELETE";
    path: "/api/v1/portfolio/corporate-actions/{action_id}";
    request: never;
    response: PortfolioDeleteResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1PortfolioFxRefresh: {
    method: "POST";
    path: "/api/v1/portfolio/fx/refresh";
    request: never;
    response: PortfolioFxRefreshResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioImportsCsvBrokers: {
    method: "GET";
    path: "/api/v1/portfolio/imports/csv/brokers";
    request: never;
    response: PortfolioImportBrokerListResponse | ErrorResponse;
  };
  postApiV1PortfolioImportsCsvCommit: {
    method: "POST";
    path: "/api/v1/portfolio/imports/csv/commit";
    request: never;
    response: PortfolioImportCommitResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1PortfolioImportsCsvParse: {
    method: "POST";
    path: "/api/v1/portfolio/imports/csv/parse";
    request: never;
    response: PortfolioImportParseResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioRisk: {
    method: "GET";
    path: "/api/v1/portfolio/risk";
    request: never;
    response: PortfolioRiskResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioSnapshot: {
    method: "GET";
    path: "/api/v1/portfolio/snapshot";
    request: never;
    response: PortfolioSnapshotResponse | ErrorResponse | HTTPValidationError;
  };
  getApiV1PortfolioTrades: {
    method: "GET";
    path: "/api/v1/portfolio/trades";
    request: never;
    response: PortfolioTradeListResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1PortfolioTrades: {
    method: "POST";
    path: "/api/v1/portfolio/trades";
    request: PortfolioTradeCreateRequest;
    response: PortfolioEventCreatedResponse | ErrorResponse | HTTPValidationError;
  };
  deleteApiV1PortfolioTradesByTradeId: {
    method: "DELETE";
    path: "/api/v1/portfolio/trades/{trade_id}";
    request: never;
    response: PortfolioDeleteResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1StocksExtractFromImage: {
    method: "POST";
    path: "/api/v1/stocks/extract-from-image";
    request: never;
    response: ExtractFromImageResponse | ErrorResponse | HTTPValidationError;
  };
  postApiV1StocksParseImport: {
    method: "POST";
    path: "/api/v1/stocks/parse-import";
    request: never;
    response: ExtractFromImageResponse | ErrorResponse;
  };
  getApiV1StocksByStockCodeHistory: {
    method: "GET";
    path: "/api/v1/stocks/{stock_code}/history";
    request: never;
    response: StockHistoryResponse | ErrorResponse;
  };
  getApiV1StocksByStockCodeQuote: {
    method: "GET";
    path: "/api/v1/stocks/{stock_code}/quote";
    request: never;
    response: StockQuote | ErrorResponse | HTTPValidationError;
  };
  getApiV1SystemConfig: {
    method: "GET";
    path: "/api/v1/system/config";
    request: never;
    response: SystemConfigResponse | ErrorResponse | HTTPValidationError;
  };
  putApiV1SystemConfig: {
    method: "PUT";
    path: "/api/v1/system/config";
    request: UpdateSystemConfigRequest;
    response: UpdateSystemConfigResponse | SystemConfigValidationErrorResponse | SystemConfigConflictResponse | HTTPValidationError | ErrorResponse;
  };
  getApiV1SystemConfigExport: {
    method: "GET";
    path: "/api/v1/system/config/export";
    request: never;
    response: ExportSystemConfigResponse | ErrorResponse;
  };
  postApiV1SystemConfigImport: {
    method: "POST";
    path: "/api/v1/system/config/import";
    request: ImportSystemConfigRequest;
    response: UpdateSystemConfigResponse | ErrorResponse | SystemConfigValidationErrorResponse | ErrorResponse | SystemConfigConflictResponse | HTTPValidationError;
  };
  postApiV1SystemConfigLlmDiscoverModels: {
    method: "POST";
    path: "/api/v1/system/config/llm/discover-models";
    request: DiscoverLLMChannelModelsRequest;
    response: DiscoverLLMChannelModelsResponse | HTTPValidationError | ErrorResponse;
  };
  postApiV1SystemConfigLlmTestChannel: {
    method: "POST";
    path: "/api/v1/system/config/llm/test-channel";
    request: TestLLMChannelRequest;
    response: TestLLMChannelResponse | HTTPValidationError | ErrorResponse;
  };
  getApiV1SystemConfigSchema: {
    method: "GET";
    path: "/api/v1/system/config/schema";
    request: never;
    response: SystemConfigSchemaResponse | ErrorResponse;
  };
  postApiV1SystemConfigValidate: {
    method: "POST";
    path: "/api/v1/system/config/validate";
    request: ValidateSystemConfigRequest;
    response: ValidateSystemConfigResponse | HTTPValidationError | ErrorResponse;
  };
  getApiV1UsageSummary: {
    method: "GET";
    path: "/api/v1/usage/summary";
    request: never;
    response: UsageSummaryResponse | HTTPValidationError;
  };
}
